accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register')
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('cart/', views.CartDetailView.as_view(), name='cart-detail-view'),
    path('order/history/', views.OrderHistoryView.as_view(), name='order-history-view'),
    path('orders/manage/', views.ManageOrdersView.as_view(), name='manage-orders-view')
]

services/urls.py
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [
    path('services/new/', views.ServiceCreateView.as_view(), name='service-create'),
    path('services/<pk>/', views.ServiceDetailView.as_view(), name='service-detail'),
    path('jobs/', views.JobListView.as_view(), name='job-list'),
    path('jobs/<pk>/', views.JobDetailView.as_view(), name='job-detail'),
    path('jobs/new', views.JobCreateView.as_view(), name='job-create'),
    path('services/categories/<name>/', views.ServiceCategoryListView.as_view(), name='category-service-list')
]

templates/_errors.html
<div id="errors-container" style="text-align:center;display:none">
    <div class="alert alert-danger" style="margin:auto;display:inline-block">
        <h2 class="card-title">
        </h2>
        <div class="">
            <ul id="errorslist">

            </ul>
        </div>
    </div>
</div>

templates/_landing_banner.html
{% load static %}
<div class="landing-intro">
    <div class="text-center align-middle">
    <img src = "{% static 'static/img/ulance.png' %}" class="img-fluid"/></br>
        <a href="{% url 'accounts:register' %}"/><span class="ulance-btn">Start Exploring Services</span>
            <a href="{% url 'accounts:register' %}"/><span class="ulance-btn">Join</span></a>
            <a href="{% url 'accounts:login' %}"><span class="ulance-btn">Login</span></a>
    </div>


    <!--<div class="row" style="display:table-cell">-->
        <!--<div class="col-md-4">-->
            <!--<p>Join</p>-->
        <!--</div>-->
    <!--</div>-->
</div>

{% include "_errors.html" %}

templates/_order_select.html
<div class="form-group">
    <select class="form-control" id="parent_category" @change="onOrderChange()" v-model="currentOrder">
        <option v-for="order in orderingList" :value="order.value">${order.label}</option>
    </select>
</div>

templates/base.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width-device-edith, initial-scale=1">
{% load sass_tags %}
<html>
<head lang="en">
    <meta charset="UTF-8">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

<!--VEX STYLE-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/vex-js/4.1.0/css/vex.min.css" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/vex-js/4.1.0/css/vex-theme-os.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/vex-js/4.1.0/css/vex-theme-top.min.css"/>

<link href='https://fonts.googleapis.com/css?family=Nunito' rel='stylesheet'>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"/>

<link href="{% sass_src 'static/scss/main.scss' %}" rel="stylesheet" type="text/css" />

<!--JQuery-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>

<!--BOOTSTRAP-->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

  <!--VEX for better promots, dialogs, etc-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/vex-js/4.1.0/js/vex.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vex-js/4.1.0/js/vex.combined.min.js"></script>

<!--Vue JS-->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue-resource@1.5.1"></script>

<script src = "{% static 'static/js/main.js' %}" ></script>
<script src = "{% static 'static/js/forms.js' %}" ></script>


</head>
<body>
{% include 'index.html' %}
{% block content %}
{% endblock content %}
</body>

</html>

templates/index.html
{% include 'navbar.html' %}
{% include 'subnav.html' %}
{% if not request.user.is_authenticated and request.get_full_path == '/' %}
{% include '_landing_banner.html' %}
{% endif %}

templates/landing_banner.html
{% load static %}
{% load staticfiles %}
<div class="landing-intro">
    <div class="text-center align-middle">
    <img src = "{% static 'static/img/ulance.png' %}" class="img-fluid"/></br>
        {% if request.user.is_authenticated %}
        <a href="{% url 'accounts:register' %}"/><span class="ulance-btn">Become a Seller</span></a>
        <a href="{% url 'accounts:register' %}"/><span class="ulance-btn">Start Exploring Services</span>
        <span class="ulance-btn logout-btn">Logout</span>
        {% else %}
            <a href="{% url 'accounts:register' %}"/><span class="ulance-btn">Join</span></a>
            <a href="{% url 'accounts:login' %}"><span class="ulance-btn">Login</span></a>
        {% endif %}
    </div>


    <!--<div class="row" style="display:table-cell">-->
        <!--<div class="col-md-4">-->
            <!--<p>Join</p>-->
        <!--</div>-->
    <!--</div>-->
</div>

{% include "_errors.html" %}

templates/navbar.html
{% load static %}
{% if request.user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top .bg-ulance-nav">
  <a class="navbar-brand nav-img" href="{% url 'index' %}"><img src="{% static 'static/img/U2_white.png' %}" class="img-fluid"/></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'services:job-list' %}">Jobs</a>
      </li>
    </ul>
    <!--<form class="form-inline my-2 my-lg-0">-->
      <!--<input class="form-control mr-sm-2" type="search" placeholder="Search For Services" aria-label="Search">-->
      <!--<button class="btn btn-sm ulance-btn my-2 my-sm-0" style="font-size:13px" type="submit">Search</button>-->
    <!--</form>-->
      <ul class="navbar-nav ml-auto right-nav" style="margin-right:5em;">
          <!--<li class="nav-item"><a class="nav-link" href="#">Orders</a></li>-->
          <li class="nav-item dropdown" style="padding-right:.9rem">
              <a class="" style="display:inline" href="#" id="profilePicDropdown" data-toggle="dropdown"><img class="profile-pic img-fluid rounded-circle" src="{{request.user.profile.profile_pic.url}}"/>
              </a>

              </a>
              <div class="dropdown-menu text-center" style="font-size:.9rem" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{{request.user.profile.get_absolute_url}}">View Profile</a>
                  <a class="dropdown-item" href="{% url 'services:service-create' %}">Create Service</a>
                  <a class="dropdown-item" href="{% url 'services:job-create' %}">Post a job</a>
                  <a class="dropdown-item" href="{% url 'orders:manage-orders-view' %}">Manage Orders</a>
                  <a class="dropdown-item" href="{% url 'orders:order-history-view' %}">Order History</a>
                  <a class="dropdown-item" href="#">Completed Orders</a>
                  <a class="dropdown-item" href="#">Account Settings</a>
                  <span class="dropdown-item logout-btn" onclick="logout()">Logout</span>
              </div>
          </li>
      </ul>
  </div>
</nav>

{% elif not request.user.is_authenticated and request.get_full_path != '/' %}
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top .bg-ulance-nav">
  <a class="navbar-brand nav-img" href="{% url 'index' %}"><img src="{% static 'static/img/U2_white.png' %}" class="img-fluid"/></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto right-nav" style="margin-right:5em;">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
      </li>
      </ul>
  </div>
</nav>

{% endif %}

templates/subnav.html
{% if request.user.is_authenticated or request.get_full_path != '/' %}
{% load static %}

<!--<div class="subnav">-->
        <!--<div class="dropdown-hover">Graphic Design-->
            <!--<div class="dropdown-content">-->
                <!--<a href="#">Hello World</a>-->
                <!--<a href="#">Hello World</a>-->
                <!--<a href="#">Hello World</a>-->
            <!--</div>-->
        <!--</div>-->
        <!--<div class="dropdown-hover">Graphic Design-->
            <!--<div class="dropdown-content">-->
                <!--<a href="#">Hello World Hello World Hello World</a>-->
                <!--<a href="#">Hello World</a>-->
                <!--<a href="#">Hello World</a>-->
            <!--</div>-->
        <!--</div>-->
    <!--</div>-->
<div class="subnav">
    <hr>
    {% for parent_category in parent_categories %}
        <div class="dropdown-hover">
            <div class="subnav-item">{{ parent_category.name }}</div>
            <div class="dropdown-content">
                {% for sub_category in parent_category.children.all %}
                    <a href="{% url 'services:category-service-list' sub_category.name %}">{{sub_category.name}}</a>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
    <hr>
</div>

{% endif %}